server:
  port: 8080
  servlet:
    context-path: /redismail

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test_mail"
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: nhatthaitn2003@gmail.com
    password: udxs gskd ozzt meyy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  