server:
  port: 8080
  servlet:
    context-path: /radiscache

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test_redis"
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379